## Intro / reading

- We're thrilled to announce the `{arcgis}` metapackage.
- `{arcgis}` is a suite of R packages focused on bringing location services directly to the #r-spatial community
- We can now take any feature service such this `USA Major Cities`
- And create a reference to it directly from R
- With a reference to that feature service,
    - we can explore all of its metadata
    - or it can be queried, and brought back into R as familiar objects

## Portal integration

- These packages also enable you to connect directly to your organization's portal
    - doing so provides you with an authorization token.
- With this token, you can manage and publish feature services all from your R console.
- With just this one line of code, we've published an {sf} object to our private portal
- That newly published service can be read in the same way
- With this integration, R can be more tightly coupled into your data pipeline

## rOpenSci bit

- The packages can be built upon as well.
- For example, the rOpenSci package {FedData} which provides access to government GIS data, has already adopted {arcgislayers} improving speed and ease of access to EPA and USGS data sources

## `{arcgisutils}`

- With the arcgis metapackage, you can build your own solutions, or, better yet, help us build new features
- Underlying all of this is {arcgisutils}
- Which simplifies authentication
- provides fast Esri JSON parsing
- and other utilities
- It is the groundwork that our future packages will be based.

## Closing

- For data scientists, we want to give you the tools to simplify your day to day.
- For the GIS analysts' whose colleagues will never leave R, this is for them.
- And for package developers, we want to make it easy to contribue.

- Thank you all.
- Back to you Lauren
